create table brand_category_price
(
    id                int auto_increment comment '브랜드별 상품 카테고리의 가격정보'
        primary key,
    brand_category_id int not null comment 'brand_category.id',
    price             int not null comment '상품가'
);

INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (1, 24, 11200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (2, 25, 5500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (3, 26, 4200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (4, 27, 9000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (5, 28, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (6, 29, 1700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (7, 30, 1800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (8, 31, 2300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (9, 32, 10500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (10, 33, 5900);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (11, 34, 3800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (12, 35, 9100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (13, 36, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (14, 37, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (15, 38, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (16, 39, 2200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (17, 40, 10000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (18, 41, 6200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (19, 42, 3300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (20, 43, 9200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (21, 44, 2200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (22, 45, 1900);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (23, 46, 2200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (24, 47, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (25, 49, 10100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (26, 50, 5100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (27, 51, 3000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (28, 52, 9500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (29, 53, 2500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (30, 54, 1600);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (31, 55, 2400);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (32, 56, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (33, 57, 10700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (34, 58, 5000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (35, 59, 3800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (36, 60, 9900);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (37, 61, 2300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (38, 62, 1800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (39, 63, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (40, 64, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (41, 65, 11200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (42, 66, 7200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (43, 67, 4000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (44, 68, 9300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (45, 69, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (46, 70, 1600);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (47, 71, 2300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (48, 72, 1900);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (49, 73, 10500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (50, 74, 5800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (51, 75, 3900);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (52, 76, 9000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (53, 77, 2200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (54, 78, 1700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (55, 79, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (56, 80, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (57, 81, 10800);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (58, 82, 6300);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (59, 83, 3100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (60, 84, 9700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (61, 85, 2100);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (62, 86, 1600);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (63, 87, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (64, 88, 2000);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (65, 89, 11400);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (66, 90, 6700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (67, 91, 3200);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (68, 92, 9500);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (69, 93, 2400);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (70, 94, 1700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (71, 95, 1700);
INSERT INTO domain_db.brand_category_price (id, brand_category_id, price) VALUES (72, 96, 2400);
